### ISSUE TITLE
Søknadsportal NNKS: felt for navn

### ISSUE THREAD

**Issue by sveinip** [olemak/liaf-theme#3]
I søknadsportalen kommer søkere nå opp med brukernavn/epost. Dette kan være mye rart. Noen ganger er det vanskelig å vite hvem folk er.

Det burde være et eget felt for å skrive inn navnet sitt øverst i søknaden.

**Comment by olemak** [comment]
Lukker denne, da den er duplikat av:
[Mangler felt for navn i søknadsportal](https://github.com/sveinip/NNKS-web-saker/issues/2)
