### ISSUE TITLE
Besøk oss info legger seg på program-sida?

### ISSUE THREAD

**Issue by sveinip** [olemak/liaf-theme#9]
Eivind oppdaterte besøk-oss-infoen og la inne et bilde.
Nå dukker denne teksten også opp på programsida:
http://liaf.no/program/

**Comment by olemak** [comment]
Alle **sider** (pages) som er knyttet til en festival/årstall legger  seg på programsiden for det året.
Jeg fjernet tilknytningen mellom 2017 og "Besøk oss"-siden, og nå er programet som det skal. 

Tanken er at "Besøk oss" er en side som kan oppdateres løpende og dermed være "evig-grønn" fremfor å være tilknyttet en bestemt festival.
